Avoid recursions in `tableView_heightOfRow_`
beeware/toga pull request #1031
Opened 2020-08-25 18:31 UTC by SamSchott

Avoid calling `tableView_viewForTableColumn_row_` from `tableView_heightOfRow_` because it leads to unnecessary initialisations of table cell views. Instead use the default row height if the cell contains only text and an icon.

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

2020-08-27 13:10 UTC, SamSchott commented
Ok, this should be ready for review now. Note the edited initial comment.

2020-08-30 01:54 UTC, freakboy3742 requested changes
This looks really solid; and it definitely looks like a performance improvement. 

I *think* I might have spotted an edge case though; although I'm not 100% sure it will actually bear out in practice. 

Historically, `setup()` was only invoked in the constructor, which means the views and constraints are only set up once.

However, in this update, `setup()` is invoked whenever `setText_()` or `setImage_()` is invoked. If I'm reading this right, that means a cell could end up with multiple image/text views, plus multiple sets of constraints.

Is that actually going to be a problem? Or is the cell completely recreated on an image/text change?

2020-08-30 08:35 UTC, SamSchott commented
The current way of running `setup` is a bit hacky, since this really should be done in the constructor. However, it should only be run once because of the check for `self.imageView`. The image view will exist if setup has already run and therefore prevent it from being run again. Maybe this is too implicit and obfuscates the actual logic. I can handle this with an additional variable such as `_needs_setup`.

Regarding the creation of cell views, my understanding is the following: when the table is loaded, a cell view is initialised for very visible cell. When the user scrolls the table, cell views which become hidden will be reused to display the now visible rows by changing their text and icon. This results in significant performance improvements, especially when first loading the table. We were not taking advantage of this because my implementation of `tableView_viewForTableColumn_row_` was forcing the creation of all views in advance.

2020-08-30 08:40 UTC, SamSchott commented
Come to think of it, I now remember why I chose the roundabout way of checking if an `imageView` already exists instead defining a variable such as `_needs_setup`. Such a variable would need to be set to False during init and the purpose of this PR was to avoid overriding init in the first place.

2020-09-12 02:00 UTC, freakboy3742 approved these changes
Ok - I think that explanation is good enough for me. At the very least, this implementation is clearly more responsive, so it's a demonstrable functional improvement.

2020-09-12 02:00 UTC, merged