Add the ability of toga.Commands to use shortcuts in Windows
beeware/toga pull request #1045
Opened 2020-09-11 16:37 UTC by saroad2

Fixes #991

## PR Checklist:

- [X] All new features have been tested
- [ ] All new features have been documented
- [X] I have read the **CONTRIBUTING.md** file
- [X] I will abide by the code of conduct

2020-09-12 01:54 UTC, freakboy3742 requested changes
Can't argue that this definitely works; I'm just not 100% convinced that it's the correct implementation. The most obvious manifestation of the problem that I see is that the menu doesn't contain the keyboard shortcut. Compare the way the Commands menu renders in Tutorial 2:

<img width="172" alt="Screen Shot 2020-09-12 at 9 42 56 am" src="https://user-images.githubusercontent.com/37345/92984395-67391c80-f4dc-11ea-90e4-1a2e2b9e9433.png">

to the way the File menu renders on Notepad:

<img width="274" alt="Screen Shot 2020-09-12 at 9 42 47 am" src="https://user-images.githubusercontent.com/37345/92984397-699b7680-f4dc-11ea-9fc0-301adce0d104.png">

I would have expected that something like the [ShortcutKeys](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.toolstripmenuitem.shortcutkeys?view=netcore-3.1) property on a menu item would capture both the creation of the annotation in the menu item, plus catching the keypress when contextually appropriate.

2020-09-12 01:54 UTC, freakboy3742 commented on src/winforms/toga_winforms/app.py
> +            self.interface.main_window._impl.native.KeyUp += self.winforms_key_press
Two questions here:
1) Is keyUp the right signal to catch? Why catch the release, not the press (i.e., keyDown)?
2) The code placement is odd to me. This doesn't affect how the code runs, but putting a keypress hander on the window in between two native app handlers seems out of place.

2020-09-12 07:14 UTC, saroad2 commented
Hey Russell, you are absolutely right! The  *ShortcutKeys* property was the right direction to go to.
Fixed that and now it works beautifully!

if you have any other errors you've found, please let me know!

2020-09-13 03:04 UTC, freakboy3742 approved these changes
Awesome - looks great!

2020-09-13 03:04 UTC, merged