set font, color, bgcolor implementations for GTK
beeware/toga pull request #1150
Opened 2020-12-05 04:57 UTC by Ksengine

added
- set_font
- set_color
- set_background_color

**Docs says**
> **Deprecated since version 3.16: Use a custom style provider and style classes instead**

just added for use other widgets without errs. change in future.

## PR Checklist:
- [ ] All new features have been tested
- [ ] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

2020-12-05 23:29 UTC, freakboy3742 requested changes
We're not going to merge a patch that uses an API that is known to be deprecated at the time of writing - we're going to need to rewrite anyway, so we might as well get it right the first time.

In addition - as I've indicated on other patches, a PR needs to include details on how you've tested the code.

2020-12-06 01:50 UTC, Ksengine commented
Its deprecated at later versions of gtk.
They are working. But shows a deprecation message on console. Without these methods. Some widgets are not working properly.
I had added warning comments on this edited lines.
Then in future someone can fix it.

2020-12-06 02:09 UTC, freakboy3742 commented
...Yes. And I'm telling you that I'm not going to merge a patch that generates deprecation warnings at time of review unless there is *literally* no other way to achieve the goal - something that is not true in this case.

2020-12-06 02:13 UTC, Ksengine commented
We can use a custom style provider and style classes instead.

2020-12-06 12:28 UTC, Ksengine commented
@freakboy3742 can you merge,or close this pr

2020-12-06 22:25 UTC, closed without merging