Implement Clipboard for Windows and Android
beeware/toga pull request #1191
Opened 2021-01-13 08:01 UTC by t-arn

This PR implements the Clipboard class, which allows us to copy and paste text on Windows and Android (and dummy).
Other platforms are currently not yet implemented because it is currently unclear how to handle data types other than Text.
I will add a feature request to discuss these issues with the community.
So, this PR is more a proof of concept and a base for further discussion.

## PR Checklist:

- [x] All new features have been tested
- [ ] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

2021-02-12 17:31 UTC, phildini commented
Hello! Thank you for this, and than you for adding an example using this, that's really neat to see.

This is the first `util` in the codebase, can you talk a bit about why you chose that path instead of fitting clipboard into the existing categories?

2021-02-14 08:22 UTC, t-arn commented
@phildini 
> This is the first `util` in the codebase, can you talk a bit about why you chose that path instead of fitting clipboard into the existing categories?

Well, for me, the clipboard didn't fit into the existing categories and I think, there will be more functionality that could go into `util` like access to camera, gps etc.

2022-04-07 06:13 UTC, freakboy3742 requested changes
This looks like a good starting point; however, there's a lot still needed.

As with @phildini, I'm not convinced the `util` module is required. As a cosmetic thing, the name "utils" implies a "we couldn't think of a better name for this bucket of stuff". In the case of other hardware like cameras and accelerometers, we have a (currently empty) `devices` folder for that purpose, but a clipboard isn't really a "device". I'd be inclined to say that clipboards are sufficiently "core" to a modern app that they are a top level module like dialogs and icons.

Also, as you flag in the PR comments, there's also a big open question about how to handle non-text content. I suspect this will need to begin with a survey of what is possible on various platforms, with a concrete proposal following from that research. An *implementation* isn't necessarily needed - a discussion document is the next step.

2022-04-11 20:42 UTC, t-arn commented
@freakboy3742 I have a general question about Toga. It started of as a GUI framework. Now, we plan to add hardware stuff (devices folder) and clipboard. Does that mean that Toga ultimately will be a general  platform framework and not just a GUI framework?

2022-04-11 23:34 UTC, freakboy3742 commented
@t-arn I'd frame Toga as an "app building" framework. The GUI is the most obvious manifestation of that, but modern devices have a lot more features than devices of old, and those features are an integral part of the "modern app experience".

2023-03-03 08:44 UTC, closed without merging