Add `dummy` as a known platform, and use it in tests
beeware/toga pull request #1534
Opened 2022-07-27 15:28 UTC by bruno-rino

Signed-off-by: Bruno Rino <bruno.rino@gmail.com>

When creating a widget in a TestCase, the factory always needs to be specified, as in:
```
        self.switch = toga.Switch(self.text,
                                  on_change=self.on_change,
                                  value=self.value,
                                  enabled=self.enabled,
                                  factory=toga_dummy.factory)
```

My suggestion is to add `dummy` to the list of know platforms, and manually set the platform in the TestCase subclass. This would avoid the repetitive `factory=toga_dummy.factory`.

I tested this against a single widget, and the test passed as intended. 

## PR Checklist:

- [ ] All new features have been tested
- [ ] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

2022-07-27 19:19 UTC, bruno-rino commented
Notes:
1. I did not update the tests themselves; I figured I would wait and see what your response was.
2. Codecov reports include switch.py and test_switch.py, which I didn't include in the commit. That puzzles me.

2022-07-28 06:39 UTC, freakboy3742 requested changes
So - I get the intent here; but the use of the factory argument is at least partially intentional. Over the years, I've learned the hard way that global variables and singletons are *always* the the hardest things to test, and area *always* the things that get in the way when you least expect it. Explicit arguments and passing of context is a 100% reliable way of avoiding those problems. 

As case in point - you haven't made any changes to tests, and the changes you *have* made looks like they should be completely passive unless you're in the dummy module... and yet Windows and GTK tests are failing. There's an import side effect that is causing those tests to start using the dummy module as the backend.

That said - I completely understand that: 
1. Remembering to pass in the factory every time is inconvenient. 
2. The current platform factory setup doesn't make it easy to explicitly choose a platform. 

While I'm not supportive of the approach taken here to set the dummy platform as an import side effect, I *would* be in favour of making it easier to set the current factory as a side effect of TestCase setup (or a pytest-style fixture).

2022-07-29 05:27 UTC, bruno-rino commented
Global variables and singletons: can't live with them, can't live without them.

Setting the current factory will always be a global operation: in the end, we're talking about overriding `sys.platform`, which is a global variable.

Using TestCase's setUp and tearDown to set and reset it would still break the platform backend tests, if those happen to run in parallel with the dummy backend tests.

Oh well.

2022-08-01 19:48 UTC, mhsmith commented
> Using TestCase's setUp and tearDown to set and reset it would still break the platform backend tests, if those happen to run in parallel with the dummy backend tests.

I don't think running tests in parallel is something we need to support: there are too many tests already that override global state.

I'm not very familiar with pytest yet, but the cleanest way I can think of doing this is to use an "autouse" fixture. Some restructuring may be necessary to make sure the fixture covers the correct set of tests.

2022-08-16 16:14 UTC, bruno-rino commented
Here is a solution using setUp and tearDown.

Sorry for all the commits. I'm failing to keep the CI happy. I can't figure out how to load toga_gtk

2022-08-17 04:00 UTC, freakboy3742 commented
`toga_gtk` can't be imported because it hasn't been installed. The CI environment is only installing toga_core and toga_dummy.

2022-08-17 15:00 UTC, bruno-rino commented
I don't know how to make codecov happy.

2022-08-17 23:10 UTC, freakboy3742 commented
Codecov is a coverage tool. When it runs the test suite, it's verifying every line of code that is actually executed - and if a line of code you've added in a patch isn't executed by the test suite, then it's untested code. 

In 2f6bca4, the blocks of code aren't ever run because you're literally telling them not to run - so, why are they in the test at all? Of course, they're in the test because that's the feature that you're adding, so they *need* to run.

As I noted previously, the toga_gtk backend isn't available because it isn't installed in the CI environment. You don't fix that by skipping the parts of the test that require toga_gtk - you fix it by *installing toga_gtk in the CI environment*. That's what the configuration files in the `.github/workflows` folder and `tox.ini` do.

Of course, it's not quite that simple, because if the test cases require toga-gtk is installed, then no developer on Windows or macOS will be able to run the test suite. So, you'll need to work out a version of the test case that verifies this behaviour in a platform independent way.

2022-08-19 10:10 UTC, bruno-rino commented
> So, you'll need to work out a version of the test case that verifies this behaviour in a platform independent way.

That's a pretty tall order, given that the tests in question are checking that the native platform still works after my changes.

The only feasible approach I can see would be to figure out a tox+github CI configuration that installs toga_gtk only for the CI run, not on developer machines. Sounds OK to you?

2022-08-21 17:35 UTC, bruno-rino commented
... or I could use mocks. 

I'm mocking toga_gtk if it fails to import.
It might be better (and self documenting) to check for github CI environment variables (see https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables), but that would make the test specific to the github CI. I don't know how much that matters.

2022-08-22 02:23 UTC, freakboy3742 requested changes
So - mocking is definitely one approach you could take; however, in this case it's incomplete. If you're on a Mac, and you run the test suite through `tox`, the tests fail - because the test environment will only install toga-core and toga-dummy, and the test is only working around the absence of toga-gtk.

Looking at the code a little closer - a simpler approach doesn't require mocking at all. The tests that are failing in CI (and in tox) are failing because `get_platform_factory()` is unable to resolve the "default" platform factory. For the purposes of the test, that's perfectly acceptable behavior; you just need to know that it *hasn't* picked up the dummy factory. On that basis, you can change the `test_get_platform_factory()` test to:
```
    def test_get_platform_factory(self):
        try:
            factory = get_platform_factory()
            self.assertIsNotNone(factory)
            self.assertNotEqual(factory, toga_dummy.factory)
        except ModuleNotFoundError:
            # The default platform factory couldn't be imported;   
            # It can't be the dummy, and the dummy isn't ever the default platform.
            pass
```
Either `get_platform_factory()` *does* return a factory, and that factory isn't the dummy; or it fails to return a factory - either way, it isn't the dummy factory, which is the behavior you need to verify (although it might be nicer if the error was a Toga-specific "UnsupportedPlatformError" rather than a generic ModuleNotFoundError, so we can rule out other edge cases such as an import problem *inside* a backend.

In terms of this specific PR, the other change that is required is proof that this actually works in a test - you've added the plumbing to support the dummy platform being picked up without explicitly using a `factory` argument, but then you're not actually using it anywhere. I don't know if you were intending to attack this in a future PR, or in a future commit to *this* PR; but at the very least, having one example of the new behavior to prove it actually works as intended would be desirable.

That said - I'm starting to wonder if there's a bigger problem here. This entire problem exists because `get_platform_factory()` uses `sys.platform` to identify which backend should be loaded. This make overriding the default behavior difficult (as testing demonstrates); however, there are other complications. For example, a third party can't write a toga-qt backend without us adding some sort of qt-detecting behavior to `get_platform_factory()`

I'm wondering if we can address this testing issue in a different way - by exploiting distutils extension points (e.g., how [Briefcase registers it's backends](https://github.com/beeware/briefcase/blob/main/src/briefcase/platforms/__init__.py)). If Toga backends registered their factories as a distutils entry point, Toga would be able to look for the backend that has registered, and just use that. In toga-core's tests, toga-dummy is the only backend that is present; on most app installs, there will be a single installed backend. This would allow users to write their own backends if they wanted, or use a backend that isn't the "toga sys.platform default". I'm not sure how distutils responds to having multiple modules register the same entry point, but that should probably be an error case regardless. I can't think of an obvious reason why you'd need multiple backends in a single virtual environment; if there *is* a good reason, I'm sure we can work out some sort of override behavior.

2022-08-22 09:59 UTC, bruno-rino commented
> I'm wondering if we can address this testing issue in a different way - by exploiting distutils extension points (e.g., how [Briefcase registers it's backends](https://github.com/beeware/briefcase/blob/main/src/briefcase/platforms/__init__.py)).

Now that's interesting. I have no experience with "distutils extension points", but I'll look into it.

Apparently, `importlib` is recommended instead (see alert box in https://setuptools.pypa.io/en/latest/pkg_resources.html).

2022-08-22 10:44 UTC, mhsmith commented
For discovering the entry_points at runtime, importlib.metadata is now recommended instead of pkg_resources. But both APIs use the same data, which ultimately comes from [setup.cfg](https://github.com/beeware/briefcase/blob/main/setup.cfg).

2022-08-22 23:59 UTC, freakboy3742 commented
@mhsmith That's a good point; I've modified the implementation use by Briefcase in beeware/briefcase#840.

2022-08-23 15:45 UTC, bruno-rino commented
In my dev environment, I actually have both toga_core and toga_dummy.

That's because I installed my dev environment following these instructions: 
https://toga.readthedocs.io/en/latest/how-to/contribute.html

Where, at some point, it reads:
```
(venv) $ pip install -e src/core
(venv) $ pip install -e src/dummy
(venv) $ pip install -e src/cocoa
```

toga_dummy is needed in order to run tests and coverage according to the instructions. 
I presume you have moved on to using only tox, and that the contribute page needs to be updated?

Using entrypoints (and having only one backend installed) will force the use of tox for running the tests. I ran tox for the first time today!
Things I am going to miss:
1. coverage reports with lines not covered. `    pytest --cov --cov-report term-missing` in `tox.ini` fixes that, but maybe you have another way?
2. run a single test while I'm developing (e.g. `python -m unittest tests.test_platform`)

---

The entrypoints would be something like this (keys taken from briefcase's setup.cfg):

```
[options.entry_points]
toga.platforms =
    # android = toga_android
    # django = toga_web
    # iOS = toga_iOS
    # linux = toga_gtk
    macOS = toga_cocoa
    # tvOS = toga_tvOS
    # watchOS = toga_watchOS
    # wearos = toga_wearOS
    # windows = toga_winforms
```

Maybe `toga.backends` is a better group name?

---

FYI: There is no uniqueness in this metadata. If two packages are defined with:
```
[options.entry_points]
toga.platforms =
    macOS = toga_cocoa
```
and
```
[options.entry_points]
toga.platforms =
    macOS = toga_swiftui
```

You'll end up with 
```
[options.entry_points]
toga.platforms =
    macOS = toga_cocoa
    macOS = toga_swiftui
```

2022-08-24 01:13 UTC, freakboy3742 commented
> In my dev environment, I actually have both toga_core and toga_dummy.

That's why I said there was likely a need to work out some sort of disambiguation behavior.
 
> toga_dummy is needed in order to run tests and coverage according to the instructions. I presume you have moved on to using only tox, and that the contribute page needs to be updated?

The current development instructions work with the current development code. The development instructions may need to be updated if we change how we register backends.
 
> Using entrypoints (and having only one backend installed) will force the use of tox for running the tests. 

Ideally, it wouldn't *force* the use of tox, but 

I ran tox for the first time today! Things I am going to miss:
> 
> 1. coverage reports with lines not covered. `    pytest --cov --cov-report term-missing` in `tox.ini` fixes that, but maybe you have another way?
> 2. run a single test while I'm developing (e.g. `python -m unittest tests.test_platform`)

If you modify L20 of the tox.ini to read `pytest --cov --cov-report term-missing {posargs}`, it will both (a) include the missing lines by default, and (b) pass on any command line arguments from tox following a `--`; so, for example, `tox -e py310 -- tests/widgets` would run just the widget tests. I'd be happy to merge a PR with that change. 

FWIW, there are some other tox-config-related fixes that are required; for example, we're not currently using tox for the tests in the individual platform backends, and we probably should be.

2022-08-25 14:10 UTC, bruno-rino commented
This is the "merged" list of entry points:
```
[options.entry_points]
toga.backends =
    android = toga_android
    iOS = toga_iOS
    linux = toga_gtk | toga_qt
    macOS = toga_cocoa | toga_qt
    tvOS = toga_tvOS
    watchOS = toga_watchOS
    wearOS = toga_wearOS
    windows = toga_winforms | toga_uwp | toga_qt
    dummy = toga_dummy
    terminal = toga_curses
    web = toga_django | toga_falcon | toga_pyramid | toga_starlette | toga_tornado | toga_web
```

The keys were taken from briefcase, but:
- I made up some keys, mainly for nursery backends ("dummy", "terminal" and "web")
- In briefcase entrypoints, there's a (commented out) "django" key, I'm using "web" instead
- "toga_qt" got 3 platform keys!
- Note that there is no "wearOS" ("wearos" in briefcase) in the nursery, or pypi

I also removed most references to `toga_dummy.factory` from the tests. Some were kept, for bind() functions

2022-08-26 01:17 UTC, freakboy3742 requested changes
I've pushed one updates to get the test suite passing on Py3.9 and Py39; there's a couple of other comments inline with some minor comments; but otherwise, this is looking fairly good. The entry point naming you've chosen all makes sense to me - the fact that qt has 3 backends is a *good* thing in my book, as it's a validation that the approach will work (as soon as someone contributes a Qt backend, anyway). A user adds toga-qt to their project, and no matter which platform they're on, the backend will match the operating system, and be selected. 

There are two major issues I can see. The first is the failures on the GTK backend - I'm guessing there's something odd going on there with platform identification.

The second is something you've flagged - the need to preserve factory references in `bind()` calls. At this point, is there *any* purpose to the `factory` argument? The "pass factory as an argument" approach existed as a way to let you be explicit about the backend in use; but if we're making the factory selection completely implicit, doesn't this mean that the factory argument becomes redundant? 

It's not just an issue in `bind()` - the `factory` argument is redundant *everywhere* AFAICT - in widgets, in get_platform_factory(), and anywhere else it's being passed around. In fact, you could probably argue that `get_platform_factory()` could be converted into a `toga.platform.factory` attribute, rather than a function invocation.

2022-08-26 12:58 UTC, bruno-rino commented
Agreed on all points.

The gtk error was a silly mistake, as you can see.

Getting rid of the `factory` argument sounds good to me; I could tackle it, but only in a couple of weeks.

2022-09-07 04:53 UTC, bruno-rino commented
Now that's just mean - codecov is punishing me for removing unused imports.

About Getting rid of the factory argument: I would break it into these steps:
- deprecate custom factory argument from get_platform_factory
- deprecate factory argument from bind() methods
- deprecate factory argument from widget constructors
- (maybe) deprecate self.factory property from widgets and others (image, icon, font, ...)

2022-09-08 04:06 UTC, freakboy3742 requested changes
Agreed the coverage failure is annoying; it seems like such an obvious case where the report is useless, and yet... 

However, I think I'm happy enough with the code that I think it's mergable. 

The only thing that needs to be updated at this point is the contribution guide. The old instructions don't mention tox at all, which is now the only easy way to run the tests. We either need to update those instructions, or provide a workaround for forcing the use of the dummy backend when running the core test suite. One option might be an environment variable to change `current_platform`; another would be an API endpoint we can invoke to *set* the current platform to `dummy` when we're in the test suite.

Longer term, I think your approach for deprecating factory makes sense. Picking it apart, we might be able to get rid of bind() entirely. `bind()` exists because we don't want to have to specify a factory on the public API interface for `Image`, `Icon` and `Command`, but we can't create an implementation until we know which factory implementation to use. This PR effectively means the factory implementation is knowable everywhere; so the need to defer instantiation of Image/Icon etc no longer exists.

2022-09-08 07:59 UTC, mhsmith commented
> The old instructions don't mention tox at all, which is now the only easy way to run the tests. We either need to update those instructions, or provide a workaround for forcing the use of the dummy backend when running the core test suite. One option might be an environment variable to change `current_platform`; another would be an API endpoint we can invoke to _set_ the current platform to `dummy` when we're in the test suite.

We need to preserve a way to repeatedly re-run some or all of the the core tests as you edit the code, and my experience is that tox is too slow for that.

Although the Toga unit tests use the standard `unittest` framework rather than pytest, they can still be run with pytest, which is what tox already does. So maybe we could use an `autouse` fixture in a `conftest` file to ensure the core unit tests always use the dummy factory, regardless of what backend packages are installed in the environment. Pytest supports both of these features even when running unittest tests (see [here](https://docs.pytest.org/en/7.1.x/how-to/unittest.html)).

2022-09-08 12:16 UTC, bruno-rino commented
I followed the deprecation plan, without deprecating the self.factory property from widgets et al. At least in widgets, it is a handy property to have. 
Interestingly, the Image class does not have it.

I added a test file just to cover the deprecation warning. I figured that will make it easier to remove later.

The bind() methods are still around, just without the factory arguments.

I addressed the unittest issue by adding an argument to TestCase.setUp()
It should be the responsibility of the test author to make sure this works, and the environment variable option puts the burden on the bug fixer.
Sounds good? For now, only test_deprecated_factory.py is using it.

2022-09-09 00:28 UTC, freakboy3742 commented
> The bind() methods are still around, just without the factory arguments.

I think this largely confirms my suspicions - that bind() is no longer required. `obj.bind()` is effectively now a late `obj._impl`; 

> I addressed the unittest issue by adding a 'toga_platform' argument to TestCase.setUp()

I'm don't think this *has* been addressed - at least, it hasn't in my testing. If I have the dummy, cocoa and iOS backends installed on my macOS machine, the core tests run using the cocoa backend, not dummy.

> It should be the responsibility of the test author to make sure the unit tests work. Using an environment variable would put the burden on the bug fixer. Sounds good? For now, only test_deprecated_factory.py is using it.

I'm not sure what you're trying to say here. Yes - of course the test author is responsible for making the unit tests work. That doesn't change the fact that any developer needs to be able to easily *run* the tests, and that a local venv with multiple backends installed is a very common development/test environment.

2022-09-12 00:14 UTC, freakboy3742 commented
> I guess I was too concise in my remark. I was trying to explain my rationale to choose an API vs environment variable approach to override the platform. I meant that I would like to avoid depending on an environment variable, because that would make it harder for developers to run the tests. For that reason, I opted for an API approach.

I'm not sure I agree that an environment variable makes it more difficult. You can set an environment variable once and it persists; you can use `direnv` or related tools to set the variable automatically in specific contexts; and you can set environment variables as part of test setup configurations. It also allows for a user to configure the environment in which an app will run without making any code modifications (which can be useful at runtime). 

However, I agree that having an API-based approach is desirable; and it isn't mutually exclusive with adding support for an environment variable (either now or later).

Either way - being able to run the core test suite when you have a platform backend in the environment is a required use case.

2022-09-12 15:25 UTC, bruno-rino commented
I guess I need to up my environment variables game. Here I was constantly using `export`, when there are tools to automate this.

I found out that in bash/zsh I can set an environment variable just for the current command. I'm happy, as a developer, doing this:
```
TOGA_PLATFORM=dummy python -m unittest
```

And I think it's the easiest suggestion to add in the docs.

---

I'm concerned about the winforms backend. It keeps timing out, and I don't know if that's my fault.
I even submitted a separate, incomplete PR (about loading images from bytes) mostly to see if the winforms issue manifested there too. But now there's this Github Actions API issue.

2022-09-27 06:51 UTC, freakboy3742 commented
> I'm concerned about the winforms backend. It keeps timing out, and I don't know if that's my fault. I even submitted a separate, incomplete PR (about loading images from bytes) mostly to see if the winforms issue manifested there too.

The problem was platform selection - the tests were running on winforms, but the test suite was trying to run the core test suite, so the core tests were running with the winforms backend. One of the tests called `info_dialog()`, and was waiting for user input.

I've modified the CI configuration to be explicit about the platform selection, and turned up verbosity when running the tests so it's a little more obvious in the logs when a single test is hanging.

2022-09-27 07:31 UTC, freakboy3742 requested changes
The implementation of TOGA_PLATFORM that you've provided addresses the immediate issue - being able to run the core test suite when you've got a platform-specific backend installed - but I'm not sure it's the right approach for the bigger problem.

What you've effectively provided is a way to override `sys.platform` so you can set the platform to 'dummy'. However, it won't let me resolve the case where I have 2 candidate backends for the same platform (e.g., a Qt backend and a GTK backend installed on Linux; or a cocoa and swiftui backend on macOS). I'd suggest a more direct `TOGA_BACKEND=toga_dummy` will be more useful in the long run.

Development documentation also needs to be updated; it still advises that you can install dummy and cocoa/gtk/winforms and run pytest.

2022-09-29 17:31 UTC, bruno-rino commented
I've changed the implementation to use `TOGA_BACKEND=toga_dummy` and updated the documentation.

There's a couple of changes I am not sure of:
- I haven't changed the [override_current_platform](https://github.com/bruno-rino/toga/blob/add_dummy_platform/src/core/toga/platform.py#L43) function to override the backend instead of the platform. At this point, I'm quite happy with the environment variable solution. I don't see the need for this function at all. What do you think? Remove?
- Some of the text in [this section](https://toga.readthedocs.io/en/latest/how-to/contribute.html#one-error-you-might-see) is still relevant, but most is not. Should I edit it?

2022-10-26 04:50 UTC, freakboy3742 approved these changes
I've made a couple of small tweaks (including addressing the points you've raised in your most recent comment); I think this is now ready to go. Thanks for the excellent work on this, and apologies for the delay in getting it merged!

2022-10-26 04:51 UTC, merged