Update coveragerc
beeware/toga pull request #1597
Opened 2022-09-29 12:33 UTC by saroad2

This PR fixes 2 issues about running unit tests:

First, It makes sure that the coverage report change **branches coverage** in addition to **lines coverage**. it does so by adding the `branch = True` line to .coveragerc file. Moreover, I specificied of abstract methods as lines that does not require coverage.

Second, this PR fixes a bug that when running unit tests via Tox, the coverage parameters are not read from the .coveragerc file correctly. This is now taken care of as the CWD directory is the root directory of the project.

## PR Checklist:

- [X] All new features have been tested
- [X] All new features have been documented
- [X] I have read the **CONTRIBUTING.md** file
- [X] I will abide by the code of conduct

2022-09-29 12:42 UTC, saroad2 commented
As we can see in the logs of the failed step, now the tests are running with branch coverage and there are some branches which are not covered :)

The reason the PR is failing is due to tests in `test_paths` that rely on `Path.cwd` and `Path.home`.
It seems like a really bad practice... I would rather mock those instead of using real directories in may tests.

I don't want to rewrite those failing tests because it seems like out of the scope of the PR.
Let me know if you want me to do something else.

2022-09-30 02:29 UTC, freakboy3742 commented
The drop in coverage isn't a problem (well... it's a problem, but not a problem that is caused by this PR :-) ). However, the failing tests *are* a problem.

Those test exist specifically to check startup behavior - to verify that when an app is started in specific ways, that the app paths that are returned are as expected. This is, by definition, very sensitive to `Path.cwd()` - because *that's at the core of what we're trying to verify*. 

These tests can't be easily mocked (or, at least, can't be *reliably* mocked), as they specifically exist to verify the behavior of the interpreter at runtime. Mocking that behavior is just too fragile, IMHO.

As for rewriting being out of scope - if a change breaks an existing test, fixing that test is 100% in scope :-)

2022-09-30 02:30 UTC, freakboy3742 requested changes
Should have left that last comment as a review comment.

2022-09-30 09:46 UTC, saroad2 commented
So I fixed the failing tests as requested.

The PR is failing on Codecov saying that this PR has decreased the coverage percentage, which is correct as designed :)

2022-10-03 05:01 UTC, freakboy3742 approved these changes
👍

2022-10-03 05:01 UTC, merged