Coverage cleanups
beeware/toga pull request #1674
Opened 2022-11-09 17:04 UTC by mhsmith

Fixes #1673.

## PR Checklist:

- [ ] All new features have been tested
- [ ] All new features have been documented
- [ ] I have read the **CONTRIBUTING.md** file
- [ ] I will abide by the code of conduct

2022-11-09 17:42 UTC, mhsmith commented
Comparing the CI coverage output between the [main branch](https://github.com/beeware/toga/actions/runs/3426088802/jobs/5707602013) and [this branch](https://github.com/beeware/toga/actions/runs/3430236616/jobs/5717040823), it appears to be identical, as expected.

2022-11-09 23:05 UTC, freakboy3742 requested changes
A nice set of cleanups, and it definitely seems to be working; however:

1. The ergonomics of the "simple developer case" aren't great. Ideally, either `tox -e py` in a project would either include a coverage report, or there would be a separate entry point like `tox -e coverage` to do the "combine and cover" dance. Needing 3 moderately complex commands with very specific arguments to work out whether my new test covers the features I've added isn't a great developer experience - especially when the usual expectation is "pytest && coverage report"
2. Whatever the instructions end up being, they need to be collected in the contribution docs, rather than buried in a config file comment.

Given that `tox -e py` is being used in each subproject to run the tests, one approach might be to add a top-level tox entry point to run tests & report coverage - `tox -e py -- core` (or `tox -e core`?)

2022-11-10 21:43 UTC, mhsmith commented
OK, I've made `tox -e py` run `coverage combine` and `coverage report` automatically, because we want to encourage developers to pay attention to this.

I've also removed the backend coverage merge job, since each backend is already reporting its own coverage. We might want to restore this if we ever start running the backends on multiple Python versions, but we should still merge each backend separately so we can start enforcing 100% coverage one backend at a time.

2022-11-11 00:48 UTC, freakboy3742 approved these changes
All looks good; however the developer docs need to be updated to reflect these changes. The dev instructions still provide instructions for manually running coverage, and don't mention tox at all. We probably want to point people at tox as the "go to" simple case for running the test suite. I'm not sure if we need to preserve the docs about TOGA_BACKEND and manually running coverage in an "expert mode" instructions; technically, that knowledge is wrapped up in the tox and CI scripts if anyone wants to go down that route, and that stops the knowledge bitrotting over time (although hopefully we're nearing the end of the big changes to repo layout).

There's also some potential overlap with #1675 and adding a `dev` extras requires, so we don't need to manually specify installing pre-commit, coverage, etc. If you want to collect all the doc updates in that PR instead of this one to avoid having edits in 2 places, I'm fine with that. On that basis, I'll mark this as approved, but not merge it; if you want to merge it as-is, consider these comments about developer instructions to be a pre-requisite for my approval on #1675.

2022-11-13 14:18 UTC, saroad2 commented
Pay attention that now all *tox.ini* scripts are now using bash, which means they will not work for Windows developers (like me)

2022-11-13 16:35 UTC, mhsmith commented
> Pay attention that all _tox.ini_ scripts are now using bash, which means they will not work for Windows developers (like me)

Good point, I'll fix that.

2022-11-13 21:46 UTC, mhsmith commented
I'm getting tired of editing 7 files whenever I make a change to this, so I've merged all the tox.ini files into the root one, with tox environments named as follows:
```
$ tox -a
py-android
py-cocoa
py-core
py-gtk
py-iOS
py-web
py-winforms
py37-android
py37-cocoa
...
```

And I've updated the documentation accordingly.

> adding a `dev` extras requires, so we don't need to manually specify installing pre-commit, coverage, etc.

Coverage commands are now all handled by tox, so there's no need to install coverage in the main virtual environment. As for pre-commit, its scope covers the whole repository, including non-Python stuff like YAML and TOML formatting. So rather than tying that to the installation of any particular package, I think it's better to keep the instructions to install that separately.

2022-11-14 01:33 UTC, freakboy3742 approved these changes
The top level `tox` config works really well for me, and the fallback case of running pytest and coverage manually isn't *that* more complicated. It's also working for my testing on Windows, so I think we can call this done.

There's some lingering questions about the contribution docs and a `dev` dependency, but I think we can continue that discussion on #1675.

2022-11-14 01:33 UTC, merged