Fixes window crash on window._impl.set_position & an issue where where webview2 shows a black bar at the side(s) when being resized/expanded.
beeware/toga pull request #1850
Opened 2023-04-08 20:06 UTC by ItsCubeTime

I recorded 2 demonstration videos & linked them in the commit descriptions.

2023-04-08 20:15 UTC, ItsCubeTime commented
Is it possible to run pre-commit via github somehow? In my case since the changes were so minor I never actually bothered to setup a new local dev repo - I made these changes directly in githubs UI based on current beeware/toga - master

2023-04-09 04:07 UTC, freakboy3742 requested changes
The change to a transparent background makes sense; however, I can't work out the problem you're describing with Location. The video with the sample program doesn't *crash* - it locks up - but you've also got `time.sleep()` in a background handler, operating at 30fps, so lockups shouldn't be unexpected. You're also performing GUI actions in a non-GUI thread, which will be problematic.

The change notes are also a problem - they should either refer to the open bug issue that they're fixing, or "self-reference" the PR if a bug doesn't exist. 

An issue ticket is also a good place to put sample code to verify a problem. While providing a video can be useful for showing off exactly what behavior is a problem, it's a lot more useful if the reviewer can reproduce the problem themselves.

2023-04-09 04:07 UTC, freakboy3742 commented on changes/1845.bugfix.rst
The number refers to the issue number in Github. Issue 1845 is an abandoned PR for GTK font loading.

2023-04-09 04:07 UTC, freakboy3742 commented on changes/1846.bugfix.rst
The number refers to the issue number in Github. Issue 1846 is a PR for GTK font loading.

2023-04-09 11:03 UTC, ItsCubeTime commented on changes/1845.bugfix.rst
Thanks for the response, indeed the window just becomes unresponsive. Modifying the test application to run using an asyncio thread instead also results in a crash if it makes any difference.

And yes, Im operating at 30 fps :) I added the test app to the PR description.

2023-04-09 11:05 UTC, ItsCubeTime commented on changes/1845.bugfix.rst
> The number refers to the issue number in Github. Issue 1845 is an abandoned PR for GTK font loading.

So in my case, what should the towncarrier files be called? Should I merge them into 1 file and name it 1850.bugfix.rst and mention both fixes in there, or should I open an issue for each fix here on github and name the files after those intead?

2023-04-09 23:24 UTC, freakboy3742 commented on changes/1845.bugfix.rst
In this case, I'd suggest opening 2 issue tickets, and referencing those 2 tickets with 2 change notes. That provides a documentation path of the 2 independent problems that have been resolved. It also provides a space to discuss the actual source of the `set_position` problem.

More generally - this is one of the reasons that a single PR should generally fix a single issue. In this case, the transparent background fix would have been an immediate merge; but it isn't clear the `set_position` fix is needed, so the transparent background fix is on hold until the set_position issue is resolved.

2023-04-09 23:41 UTC, freakboy3742 commented on changes/1845.bugfix.rst
> Thanks for the response, indeed the window just becomes unresponsive. Modifying the test application to run in the asyncio event loop (using `asyncio.get_event_loop().run_in_executor(None, set_pos_async)`) instead also results in a window hang, if it makes any difference.

Well, yes... but:
1) You're making a call on `time.sleep()`, which is a blocking method. By definition, your app won't be updating during this call. I don't know why using `set_Position` seems to fix this in your case, but I'd guess it's almost accidental.
2) You're making a call directly on the impl layer, rather than using `window.position` on the interface, and
3) You're making a call on a GUI method from the non-GUI thread. The exact consequences of this vary from platform to platform, but it's definitely unreliable behavior.

It's still not entirely clear to me what you're trying to do, but the best interpretation of your sample program done "right" would be something like:
```
import asyncio

async def set_position(app, **kwargs):
    while True:
        await asyncio.sleep(5)
        app.main_window.position = (300, 300)
        await asyncio.sleep(1/30)
        app.main_window.position = (300, 300)
```

Then, in your `startup()` method:
```
self.add_background_task(set_position)
```

2023-05-03 02:39 UTC, freakboy3742 approved these changes
I've reverted the Location change, and corrected the changenote reference.

2023-05-03 03:26 UTC, merged

2023-05-03 11:03 UTC, ItsCubeTime commented
Thanks for merging, still I believe using the setter methods might be better. Ive been playing around a fair lot with the winAPI locally and generally speaking been encountering more issues when assigning values with the `=` operator than with the setter counterparts.

For the software Im running locally I in fact cant move my window around the way I am without using the setter (without the window hanging up permanently).  I havent encountered any issues as a result of using the setters so far, from many hours of testing.

2023-05-03 23:10 UTC, freakboy3742 commented
As I mentioned on #1856, all signs point to the problem being with the way you've written your code, not Toga. The fact that the getter/setter form "works better" seems almost accidental. There may be a deep internal reason why getters/setters appear to perform better in your case; but the "real fix" is to restructure your own code to fix the underlying problem.