Add a `clear` method that removes all children.
beeware/toga pull request #1893
Opened 2023-04-24 16:38 UTC by malikoth

Fixes #1828 

## PR Checklist:

- [ ] All new features have been tested
- [ ] All new features have been documented
- [ ] I have read the **CONTRIBUTING.md** file
- [ ] I will abide by the code of conduct

2023-04-24 16:57 UTC, freakboy3742 requested changes
This implementation looks good; now we just need the rest of the owl :-)

Two pieces are missing:
1. A change note - a file in the `changes` directory that provides the release note for this improvement. See [the contribution guide](https://toga.readthedocs.io/en/stable/how-to/contribute-code.html#add-change-information-for-release-notes) for details on what is needed
2. A test. core/tests/widgets/test_base.py has a suite of tests validating that child removal works; we need an additional set of tests for this new API. We need to validate that clear works for (a) a widget that has children, (b) a widget that *can* have children, but doesn't; and (c) a leaf node that can't have children.

2023-04-24 17:10 UTC, malikoth commented
Yup, just working through the contribution guide, little bit at a time.  :)

2023-04-24 17:16 UTC, malikoth commented
The base widget documentation includes this block:

```rst
Reference
---------

.. autoclass:: toga.widgets.base.Widget
   :members:
   :undoc-members:
   :inherited-members:
```

Am I to understand that this will automatically slurp up the docstring of my new method and I don't need to manually do anything for this new method to be documented?

2023-04-24 17:44 UTC, malikoth commented
@freakboy3742 I think this is ready for re-review.  よろしくお願いします!

2023-04-24 18:38 UTC, malikoth commented
OK, so the Travertino `Widget.clear` docs say that calling `clear` on a leaf node raises `ValueError`.  My code does not do that, but then again... despite what the docs say, _neither does `Widget.clear`.  What is the best resolution?

Raising the error is preferable to silently doing a noop, right?

2023-04-24 19:11 UTC, freakboy3742 approved these changes
Looks good to me! Thanks for the fix!

2023-04-24 19:11 UTC, merged

2023-06-06 21:57 UTC, wafaa09 commented
Hello! I don't mean to be inpatient, but if this feature will be done soon, I also don't want to spend time completing my project when this is exactly what I need! Is there a timeline for completion? I saw that there were a couple things left to do, but not sure how long that will take.
Thank you!

2023-06-06 22:12 UTC, freakboy3742 commented
@wafaa09 Umm... the PR has been merged. It's done. It hasn't been *released* in a stable release of Toga, but there's no more work to be done. If you want a pre-release version you can install the `main` branch of Toga from the git repository.

2023-06-06 22:40 UTC, wafaa09 commented
Awesome, thank you for letting me know!