Fixed `current_window` bug on winforms
beeware/toga pull request #1899
Opened 2023-04-25 01:59 UTC by proneon267

Fixed `current_window` bug on winforms and relates to #1895 
## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

2023-04-25 15:48 UTC, freakboy3742 requested changes
Tweak required to the change note, but this should be good to go.

2023-04-25 15:48 UTC, freakboy3742 commented on changes/1895.bugfix.rst
> +Modified to properly implement `current_window` on windows platform.
This should be a misc, not bug fix; it's an update to a bugfix that is already listed in the in-progress release.
```suggestion
The implementation of ``current_window`` on Winforms was corrected.
```

2023-04-26 02:01 UTC, proneon267 commented
@freakboy3742 The testbed of linux is failing and the error seems to be related to briefcase and not the code itself. Please take a look at this.

2023-04-26 16:43 UTC, freakboy3742 approved these changes

2023-04-26 17:00 UTC, merged