Added basic documentation for async function to update progress bar
beeware/toga pull request #1936
Opened 2023-05-08 09:54 UTC by LunaMeadows

Made changes to the progressbar.rst file to add basic documentation explaining how to use the progress bar in a way to not block the GUI loop. A more in depth explanation and example could be useful but I feel would take up a lot of space on the reference page and a topic guide on it would be a better place for it. 

Clears up confusion on how to use the progress bar widget

#1232 

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

2023-05-08 23:43 UTC, freakboy3742 requested changes
I'm not sure this is right for the API guide. The "without blocking" comment will either make perfect sense, or be completely meaningless, depending on where the reader is coming from.  The example has all the appearances of a complete code snippet (by including a main method), but the code won't actually run if you try, because it doesn't all the requirements of a startup method. It also doesn't include any code to... update the progress bar :-)

1. The reference guide should have a comment to the effect that "the value of the progress bar can be updated by setting the `value` attribute to any numerical value in the range `(0,max)`; however, you must be careful not to block the main event loop while performing these updates - (this reference guide) contains details on the role of the event loop in Toga apps."

2023-05-09 01:13 UTC, LunaMeadows commented
I realized I forgot the code to update the progress bar right as I was falling asleep so I apologize for that.

2023-05-09 22:12 UTC, mhsmith commented
> however, you must be careful not to block the main event loop while performing these updates

The same is true of every other widget property, e.g. the text of a label, but a progress bar is one of the most likely places to make this mistake, so a complete example might be useful.

2023-09-18 01:38 UTC, freakboy3742 commented
Closing due to a lack of activity. There's definitely still a need for a good example of this sort of use case, but given the widespread updates to the docs, it's probably easier to start this PR from scratch at this point.

2023-09-18 01:38 UTC, closed without merging