Unify ID creation
beeware/toga pull request #2044
Opened 2023-07-22 12:29 UTC by NMertsch

This PR unifies how App/Window/Widget IDs are created and documented, and ensures that the ID is always a string.

## PR Checklist:

- [ ] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

2023-07-22 12:34 UTC, freakboy3742 requested changes
Looks like a good cleanup; there's a minor tweak that can be made to the docstrings. The doctoring on app.py looks like it was historically wrong because it didn't have a type annotation.

2023-07-22 12:34 UTC, freakboy3742 commented on core/src/toga/widgets/base.py
> +        :returns: A DOM identifier for the widget.
Properties don't need a return type; the type annotation of the property is displayed in the documentation.
```suggestion
```

2023-07-22 12:34 UTC, freakboy3742 commented on core/src/toga/window.py
> +        :returns: A DOM identifier for the window.
```suggestion
```

2023-07-23 16:13 UTC, freakboy3742 commented
FYI: The Linux CI failure will be fixed by #2052. The Android CI failure will be fixed by beeware/briefcase#1380.

2023-07-26 06:58 UTC, freakboy3742 approved these changes
Thanks for these improvements. I've made a couple of minor tweaks to wording and naming of the new protocols, but otherwise this looks great - and will make the task of rolling out the analogous changes to other widget classes a lot easier (as we now have a template to follow).

Out of interest - did you log the bug with Sphinx around the `:rtype:` spelling error? I found a little more detail on this one - if you have *any* `:param:` or `:returns:` declaration, the "spelling error" goes away (e.g., adding a `:param widget:` declaration to the OnPress handler fixes the spelling error with the `None` return type.

2023-07-26 07:25 UTC, merged

2023-07-27 21:39 UTC, NMertsch commented
Looks great, thank you!

@freakboy3742 yes, I reported it here: https://github.com/sphinx-contrib/spelling/issues/216

It seems to be caused by the autoprocol plugin. Won't have time to investigate it in the next days, though.