DRAFT: use Chaquopy syntax directly in the android folder
beeware/toga pull request #2129
Opened 2023-09-21 13:37 UTC by dgmouris

Trying to remove references to `toga_android.libs` by importing from chaquopy directly.

https://github.com/beeware/toga/issues/1980

## PR Checklist:

- [ ] All new features have been tested
- [ ] All new features have been documented
- [ ] I have read the **CONTRIBUTING.md** file
- [ ] I will abide by the code of conduct

2023-09-22 21:35 UTC, dgmouris commented
Tests run so far for reference: 

```
briefcase run android -r --test -- tests/widgets/test_base.py
briefcase run android -r --test -- tests/widgets/test_box.py
briefcase run android -r --test -- tests/widgets/test_button.py
briefcase run android -r --test -- tests/widgets/test_dateinput.py
briefcase run android -r --test -- tests/test_images.py
briefcase run android -r --test -- tests/test_icons.py
briefcase run android -r --test -- tests/test_fonts.py
briefcase run android -r --test -- tests/test_paths.py

briefcase run android -r --test -- tests/widgets/test_detailedlist.py
briefcase run android -r --test -- tests/widgets/test_imageview.py
briefcase run android -r --test -- tests/widgets/test_label.py
briefcase run android -r --test -- tests/widgets/test_multilinetextinput.py
briefcase run android -r --test -- tests/widgets/test_numberinput.py
briefcase run android -r --test -- tests/widgets/test_passwordinput.py
briefcase run android -r --test -- tests/widgets/test_progressbar.py
briefcase run android -r --test -- tests/widgets/test_scrollcontainer.py
briefcase run android -r --test -- tests/widgets/test_selection.py
briefcase run android -r --test -- tests/widgets/test_slider.py
```

2023-09-22 21:49 UTC, freakboy3742 commented
Looking good; as a quick note, if you [add a change note file to your PR](https://toga.readthedocs.io/en/stable/how-to/contribute-code.html#add-change-information-for-release-notes), CI will run the full testbed suite when you push your code to GitHub. Right now, it's failing tests early because there's no change note.

2023-09-22 22:38 UTC, dgmouris commented
@freakboy3742 I think I've tested everything.

The only parts I'm not sure about being tested are:
- `toga_android/dialogs.py`
- `toga_android/container.py`

I think they are tests from the tests that I ran in the above comment.

Besides that I'm going to remove the "DRAFT" from the PR as I *fairly sure* this might be good to go pending a review:)

Thanks for the help!

2023-09-22 22:54 UTC, freakboy3742 commented
Container won't require any specific checks; it's tested implicitly by every other "put a widget on the screen" test.

Dialogs can be checked manually by running the "dialogs" example. PR #2058 will add automated checks, but that hasn't been updated for Android yet.

The one thing I noticed in a quick pass over this PR is the one thing that will prove the migration is complete: deleting the `libs` module. If the conversion to native imports is complete, the aliases in that module should be redundant.

2023-09-23 09:42 UTC, mhsmith commented
Also, I see there's a couple of CI failures in test_button (follow the "testbed (android)" link below):
```
I/python.stdout:   File "/data/data/org.beeware.toga.testbed/files/chaquopy/AssetFinder/requirements/toga_android/widgets/base.py", line 162, in set_background_filter
I/python.stdout:     native_color(value), dynamic_proxy(PorterDuff.Mode).SRC_IN
I/python.stdout:   File "proxy.pxi", line 50, in java.chaquopy.dynamic_proxy
I/python.stdout: TypeError: <class 'android.graphics.PorterDuff$Mode'> is not a Java interface
```

`dynamic_proxy` should only be used in `class` headers, and then only on classes which were previously imported using `JavaInterface` as opposed to `JavaClass`.

2023-09-23 16:34 UTC, dgmouris commented
> Also, I see there's a couple of CI failures in test_button (follow the "testbed (android)" link below):
> 
> ```
> I/python.stdout:   File "/data/data/org.beeware.toga.testbed/files/chaquopy/AssetFinder/requirements/toga_android/widgets/base.py", line 162, in set_background_filter
> I/python.stdout:     native_color(value), dynamic_proxy(PorterDuff.Mode).SRC_IN
> I/python.stdout:   File "proxy.pxi", line 50, in java.chaquopy.dynamic_proxy
> I/python.stdout: TypeError: <class 'android.graphics.PorterDuff$Mode'> is not a Java interface
> ```
> 
> `dynamic_proxy` should only be used in `class` headers, and then only on classes which were previously imported using `JavaInterface` as opposed to `JavaClass`.

Thank you! I was fumbling my way around until I had a bit of deeper understanding later on as I was testing it.

I'll update this shortly with both updates (updating this dynamic_proxy, and removing libs).

I really appreciate the help again folks @freakboy3742 and @mhsmith !

2023-09-25 17:08 UTC, dgmouris commented
@freakboy3742 @mhsmith I'm sure you folks are aware of this and I think it was discussed in the discord but there is no `testbed/test_canvas.py`. I have changed this file, although there are no tests at this current moment in time.

It seems to be in the works, based on the discord discussion.

2023-09-25 22:13 UTC, dgmouris commented
The only errors that I get with this PR is 
```
I/python.stdout: tests/test_paths.py::test_app_paths[config] 
I/python.stdout: ERROR                        [  5%]
I/python.stdout: 
I/python.stdout: tests/test_paths.py::test_app_paths[data] 
I/python.stdout: ERROR                          [  5%]
I/python.stdout: 
I/python.stdout: tests/test_paths.py::test_app_paths[cache] 
I/python.stdout: ERROR                         [  6%]
I/python.stdout: 
I/python.stdout: tests/test_paths.py::test_app_paths[logs] 
I/python.stdout: ERROR                          [  6%]
I/python.stdout: 
```
I get these tests to pass locally... I can't trigger this action to run again here unless I add another commit. 

I've removed the `libs` and everything here is exclusively using `chaquopy`. Let em know if there's anything I'm missing for issue #1980 but it seems like it covers it :) 

Thanks again for the help.

2023-09-25 22:15 UTC, dgmouris commented
On a separate note this PR affects https://github.com/beeware/toga/pull/2130

2023-09-25 22:40 UTC, freakboy3742 requested changes
I've flagged a couple of minor things inline, but otherwise, this looks like a thorough set of changes. Nice work!

The test failures you're seeing look like they've been caused by the final removal of the libs directory. There's [one last reference to `toga_android.libs` in the `tests_backend` folder](https://github.com/beeware/toga/blob/61c68a7f4a93f2df5a2a485b880941fa19ed4597/android/tests_backend/app.py#L3). I'm guessing it's passing for you locally because of a stale `.pyc` file or resource in your build. A clean build (including deleting the app from your phone/emulator) should reproduce the bug.

There's one closely related change that might also be possible as part of this - [removing `rubicon-java` as a package requirement](https://github.com/beeware/toga/blob/61c68a7f4a93f2df5a2a485b880941fa19ed4597/android/setup.py#L9). Now that we're not using Rubicon syntax, I *think* we may be able to finish the job and remove Rubicon as a package requirement. I'm not 100% certain about this - there might be one or two subtle uses that are lingering - but if we're in a position to remove it, we should. However, if it turns out things start exploding when you remove this requirement, and the fix isn't immediately obvious, that's not a blocker to merging what you've got here.

2023-09-25 22:40 UTC, freakboy3742 commented on android/src/toga_android/widgets/progressbar.py
> +# from ..libs.android import R__attr
The old imports can all be removed here

2023-09-25 22:40 UTC, freakboy3742 commented on changes/1980.misc.rst
> +Use Chaquopy instead of the toga_android.libs (which uses jubicon) for the android implementation.
```suggestion
References to Android system libraries have been modified to use Chaquopy native syntax, rather than Rubicon Java.
```

2023-09-26 09:04 UTC, mhsmith commented
> There's one closely related change that might also be possible as part of this - [removing `rubicon-java` as a package requirement](https://github.com/beeware/toga/blob/61c68a7f4a93f2df5a2a485b880941fa19ed4597/android/setup.py#L9). Now that we're not using Rubicon syntax, I _think_ we may be able to finish the job and remove Rubicon as a package requirement. I'm not 100% certain about this - there might be one or two subtle uses that are lingering - but if we're in a position to remove it, we should.

I've already removed the calls to `__global__`, since Chaquopy ensures all Java objects exposed to Python code use global JNI references. So I think the only remaining use of Rubicon (probably the only remaining appearance of the *word* "rubicon" on this PR's branch) is the import of `android_events` in toga_android/app.py. 

This file currently lives in [the Briefcase Android template](https://github.com/beeware/briefcase-android-gradle-template/blob/main/%7B%7B%20cookiecutter.format%20%7D%7D/app/src/main/python-briefcase/rubicon/java/android_events.py), so to make it easier to update, it should be copied into toga_android. The copy in the template should be left alone for now, because it's needed by older versions of Toga.

2023-09-26 16:13 UTC, mhsmith commented
Thanks, it's been our main focus for the last 6 months.

Do you want to do the last couple of things mentioned above?
* Removing rubicon_java from setup.py
* Copying android_events.py into Toga, and updating it to use the new import syntax

I think those are the only remaining references to "rubicon" in the `android` folder, so it would make sense to remove them in this PR. But if not, I'm happy to merge it as it is.

2023-09-26 23:53 UTC, freakboy3742 commented
> * Copying android_events.py into toga_android, and updating it to use the new import syntax

Ironically, this is a module that *will* need to be in `toga_android.libs`, similar to the [`proactor.py` module in Winforms](https://github.com/beeware/toga/blob/main/winforms/src/toga_winforms/libs/proactor.py). The reference to the original rubicon version in app.py will need to be updated as well.

2023-09-27 18:05 UTC, dgmouris commented
> > * Copying android_events.py into toga_android, and updating it to use the new import syntax
> 
> Ironically, this is a module that _will_ need to be in `toga_android.libs`, similar to the [`proactor.py` module in Winforms](https://github.com/beeware/toga/blob/main/winforms/src/toga_winforms/libs/proactor.py). The reference to the original Rubicon version in app.py will need to be updated as well.

I didn't read this before I did my most recent push to remove the Rubicon requirement. I can remove it if needed, no problem there.

If I'm not mistaken you folks are discussing using a similar approach to https://github.com/beeware/toga/blob/be64fbbe289f66470c2ce3a8010968a6d778f25b/winforms/src/toga_winforms/libs/proactor.py#L11 in the toga repo except using [the briefcase android event loop](https://github.com/beeware/briefcase-android-gradle-template/blob/v0.3.14/%7B%7B%20cookiecutter.format%20%7D%7D/app/src/main/python-briefcase/rubicon/java/android_events.py) to use chaquopy in `toga_android.libs`

IMO the easiest path forward for this would be to:
1. merge this as it's getting without removing Rubicon (I'll remove that commit)
1. create a new PR to add the event loop (as we'll probably add `toga_android.libs` for the event loop. (I'd be happy to hack away on this as well and learn a bit about briefcase) and remove Rubicon for the Android template
1. create a new PR in [briefcase](https://github.com/beeware/briefcase-android-gradle-template/tree/main) to remove it (but I'm not sure about the repercussions tbh.

I'm good with either way:) Let me know what you folks think @mhsmith and @freakboy3742

2023-09-27 21:50 UTC, mhsmith commented
Moving over android_events.py should be pretty simple, so I'll do it myself now.

2023-09-27 22:51 UTC, mhsmith approved these changes

2023-09-27 23:12 UTC, freakboy3742 approved these changes
Looks like Malcolm has pushed the ball the last couple of inches - so I think this is done! Thanks for the contribution - there's a lot of work here, and it significantly improves the readability of the Android codebase.

2023-09-27 23:12 UTC, merged

2023-09-29 21:07 UTC, t-arn commented
> On a separate note this PR affects https://github.com/beeware/toga/pull/2130

Noted, thanks. I'll do a merge when I finalize the PR.