Disabling suggestions on Android if readonly mode is set.
beeware/toga pull request #2139
Opened 2023-09-28 13:57 UTC by Aarontheissueguy

Set "TYPE_TEXT_FLAG_NO_SUGGESTIONS" as "InputType" if "readonly" is True and testing it in the backend probe

This ensures that no spelling suggestions are made if a text is set to readonly. This relates to #2136

2023-09-28 23:34 UTC, freakboy3742 requested changes
Looks good, and works well in my testing.

There's a couple of things standing in the way of me merging this:
1. When you submit a PR that closes a ticket, you need to include the text `Fixes #xxx` in the PR description; this is the trigger to Github to close the issue when the PR is merged. I've made this modification on your behalf.
2. Toga's CI requires that every PR include [a changenote](https://toga.readthedocs.io/en/stable/how-to/contribute-code.html#add-change-information-for-release-notes) - this is why CI is currently failing. In this case, we need a file named `changes/2136.bugfix.rst` , with a single line of content that reads something like "Multiline text inputs no longer show spelling suggestions when in readonly mode."
3. When you submit a PR, it's really helpful if you submit the PR from a *branch* of your fork, rather than the main branch. The missing changenote is a fairly minor thing, so ordinarily I would add it myself as part of the review process - but because you've submitted from your `main` branch, I can't do that: maintainers can edit PRs submitted from a *branch*, but not PRs submitted from your main. Submitting from a branch also makes *your* life easier in the long run, because it allows you to have multiple PRs in flight at the same time (after all, you can only have 1 main) - but once your PR is merged, it also means the reconciliation process is easier, because your fork's mainline can stay a "clean" copy of  the upstream repository, rather than something you need to merge or rebase.

There's no need to re-work this PR to be from a different branch; if you add the changenote, I'll be happy to merge it. But it's worth keeping in mind for next time.

2023-09-29 10:30 UTC, Aarontheissueguy commented
Thanks for the tips, I will keep them in mind the next time I contribute. I added the changenote as requested.

2023-09-29 12:02 UTC, freakboy3742 commented
Getting closer - now the PR is hitting a pre-commit issue. We apply black formatting to format our code, and we check that every commit has had black applied. If you follow the [contributors guide](https://toga.readthedocs.io/en/stable/how-to/contribute-code.html#set-up-your-development-environment) you can install pre-commit locally, and have these fixes applied automatically when you commit code. In this case, you'll need to run `pre-commit run --all` over your code to apply the fixes to previous commits.

2023-09-29 22:21 UTC, freakboy3742 commented
Ok - now we're at a "real" problem, not just a cosmetic one: The test you've added is failing in CI.

2023-09-30 09:58 UTC, Aarontheissueguy commented
hmm... Il look into it. Not entirely sure what causes this though.

2023-10-01 23:28 UTC, freakboy3742 commented on android/tests_backend/widgets/textinput.py
> +            )
The `readonly` property is not *asserting* that the widget is readonly - it is returning the current readonly status (hence the `return not focusable`). This test is asserting that TYPE_TEXT_FLAG_NO_SUGGESTIONS is *always* set. 

```suggestion
        if input_type & InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS:
            # TYPE_TEXT_FLAG_NO_SUGGESTIONS is set
            if focusable:
                raise ValueError(
                    "TYPE_TEXT_FLAG_NO_SUGGESTIONS is not set on the input."
                )
        else:
            # TYPE_TEXT_FLAG_NO_SUGGESTIONS is not set
            if not focusable:
                raise ValueError(
                    "TYPE_TEXT_FLAG_NO_SUGGESTIONS has been set when the input is readonly."
                )
```

2023-10-03 09:29 UTC, Aarontheissueguy commented
Thats weird, we didn't tamper with anything iOS related, did we?

2023-10-03 09:48 UTC, freakboy3742 commented
The good news (for you) is that the iOS failure has nothing to do with you. I landed an unrelated change to Briefcase this morning, and that is causing problems with Toga's CI.

2023-10-04 03:56 UTC, freakboy3742 approved these changes
The CI problem has now been fixed - so this is good to land! 

Thanks for contribution!

2023-10-04 03:56 UTC, merged