Test undo/redo behaviour of text input widgets on macOS.
beeware/toga pull request #2151
Opened 2023-10-10 18:26 UTC by bruno-rino

Widgets tested are:
- TextInput
- MultilineTextInput
- PasswordInput
- NumberInput

The cocoa MultilineTextInput widget has been updated to enable undo.

Replaces PR https://github.com/beeware/toga/pull/2037

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

2023-10-10 18:30 UTC, bruno-rino commented
This second try was easier. Previously, the `NSEvent.keyEventWithType` function was ignoring `modifierFlags` if the `characters` parameter was a single character... My solution was to set that parameter to None. You seem to have found a better solution.

2023-10-11 07:58 UTC, freakboy3742 requested changes
This looks really good. I've dropped a couple of minor comments inline; once those are cleaned up, this should be good to land! Thanks!

2023-10-11 07:58 UTC, freakboy3742 commented on changes/2151.feature.rst
> +The cocoa MultilineTextInput widget has been updated to enable undo
```suggestion
Text input widgets on macOS now support undo and redo.
```

2023-10-11 07:58 UTC, freakboy3742 commented on android/tests_backend/widgets/base.py
> +        raise NotImplementedError()
Right idea, slightly wrong implementation. If you make the body of this method `pytest.skip()`, then the test will be skipped on Android as soon as the test tries to invoke it, removing the need to explicitly skip the platforms in the test itself. See [canvas on Android](https://github.com/beeware/toga/blob/main/android/tests_backend/widgets/canvas.py#L39) for an example.

2023-10-11 11:02 UTC, bruno-rino commented
A question of style: do you prefer the call to be `pytest.skip()` or just `skip()`? I can see mostly `pytest.skip()` in the source, but `xfail()` is always not namespaced.

2023-10-11 11:19 UTC, freakboy3742 commented
> A question of style: I am adding `skip` to another method that needs it. Do you prefer the call to be `pytest.skip()` or just `skip()`? I can see mostly `pytest.skip()` in the source, but `xfail()` is always not namespaced.

My personal preference is `pytest.skip()`; but that's in the category of "strong opinion, weakly held". It has essentially come down to who is writing a module as to which form is used. If there's an existing usage in the file, stick to that form; if there's not, it's dealer's choice :-)

2023-10-12 07:27 UTC, freakboy3742 approved these changes
Awesome - thanks!

2023-10-12 07:28 UTC, merged