Fix and tests for tree node modifications prior to expansion
beeware/toga pull request #2439
Opened 2024-03-03 05:54 UTC by reefwing

Appending/inserting/changing/removing a tree data node prior to its expansion was throwing an AttributeError.  As an optimisation, objects representing tree nodes are created on first render. Trying to access these prior to tree expansion is causing the issue.

Added a node_impl() method that can be used anywhere that the user requests node._impl, and ensures that the impl exists.

Fixes #2432.

## PR Checklist:

- [x ] All new features have been tested
- [x ] All new features have been documented
- [x ] I have read the **CONTRIBUTING.md** file
- [x ] I will abide by the code of conduct

2024-03-05 07:15 UTC, freakboy3742 requested changes
This looks really good - nice work!

I've made a couple of suggestions inline; these are mostly minor stylistic changes and some tweaks to some descriptions.

I can see 2 substantive changes that are required - both additional tests.

The first is to exercise the case of adding a child to a hidden child. The tests you've added validate that adding a child to a visible, but non-expanded root work; but you can also add a node to a child that has *never* been visible. The implementation you've provided should work for this case; but it's not explicitly tested.

The test doesn't need to do much - something like: 
```
    widget.data[0][5].append({"a": "AXX", "b": "BXX", "c": "CXX"})
```
after adding the row to the non-expanded root (around L550), plus some subsequent content and child count checks.

The second check is that once you've finished adding nodes to non-visible nodes and non-expanded roots, you can successfully expand the tree and see the result of all your changes.

As an aside - I don't know if this was intentional, but you appear to have turned off permissions for project maintainers to commit to your PR branch. Ordinarily I would have been happy to add these extra tweaks myself rather than go through a re-review; but in this case, I can't push to your branch. Regardless of whether it's intentional or accidental, it's not problem - it just means I can't do a quick tweak and merge. If nothing else, now you get the satisfaction of saying you did the *whole* patch :-)

2024-03-05 07:15 UTC, freakboy3742 commented on testbed/tests/widgets/test_tree.py
> +    # Append a row to the table
```suggestion
    # Append a child to a non-expanded root
```

2024-03-05 07:15 UTC, freakboy3742 commented on testbed/tests/widgets/test_tree.py
> +    await probe.redraw("Full row has been appended")
```suggestion
    await probe.redraw("Full row has been appended to a non-expanded root")
```

2024-03-05 07:15 UTC, freakboy3742 commented on testbed/tests/widgets/test_tree.py
> +    await probe.redraw("Partial row has been appended")
```suggestion
    await probe.redraw("Partial row has been appended to a non-expanded root")
```

2024-03-05 07:15 UTC, freakboy3742 commented on testbed/tests/widgets/test_tree.py
> +    await probe.redraw("Partial row has been updated")
```suggestion
    await probe.redraw("Partial non-visible row has been updated")
```

2024-03-05 07:15 UTC, freakboy3742 commented on testbed/tests/widgets/test_tree.py
> +    await probe.redraw("Row has been removed")
```suggestion
    await probe.redraw("Non-visible row has been removed")
```

2024-03-05 07:52 UTC, reefwing commented
Thanks for the support and kind words. It was definitely not intentional to turn off project maintainers commit permission. In fact I don't know how I did that!

2024-03-06 08:00 UTC, reefwing commented
@freakboy3742 - I've made the selected changes. For some reason I can't edit the PR to allow you to commit changes. I suspect I had the wrong box checked when creating the PR. I'll keep an eye out for this next time.

2024-03-06 22:22 UTC, freakboy3742 approved these changes
Looks great - Thanks for the contribution!

2024-03-06 22:22 UTC, merged