Fixes Winforms Progressbar
beeware/toga pull request #2485
Opened 2024-04-06 08:47 UTC by SahilNagpure07

Fixes #2430

## PR Checklist:

- [ ] All new features have been tested
- [ ] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

2024-04-06 20:12 UTC, proneon267 commented
Just a heads up, #2430 is covered by #2484

2024-04-08 01:18 UTC, freakboy3742 requested changes
Thanks for the PR. It's currently failing CI because it's [missing a changenote](https://toga.readthedocs.io/en/stable/how-to/contribute-code.html). It's also unclear if this will impact on tests - it feels like there *should* be an impact on tests.

2024-04-12 06:44 UTC, freakboy3742 commented
FYI - you can ignore the test failures on Python 3.13 - there's been a regression in Freezegun that is incompatible with Python 3.13.0a6; the fix has been made upstream, but we're waiting on an updated release.

However, the test failure on iOS *does* need to be resolved. You'll need to investigate why that test is failing and work around the issue.

2025-06-21 23:18 UTC, johnzhou721 commented
@freakboy3742 Is this still relevant? Need for ``_background_supports_alpha`` is eliminated in #2484, it seems.

2025-06-22 06:03 UTC, freakboy3742 commented
Yes, it seems like this has been fixed.

2025-06-22 06:03 UTC, closed without merging